config/routes.rb
Tracky::Application.routes.draw do
  
  get 'myspecs/coding'
  get 'myspecs/stylingcss'
  get 'myspecs/stylinghtml'
  get 'myspecs/userfriendly'
  get 'myspecs/cucumber'
  resources :myspecs

  root :to => 'myspecs#index'

end

app/models/myspec.rb
class Myspec < ActiveRecord::Base
  attr_accessible :commit, :cucumber, :function, :status, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/myspecs_controller.rb
class MyspecsController < ApplicationController
  # GET /myspecs
  # GET /myspecs.json
  def index
    @myspecs = Myspec.find(:all, :order => 'core DESC, overall_status, title')  

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @myspecs }
    end
  end

  # GET /myspecs/1
  # GET /myspecs/1.json
  def show
    @myspec = Myspec.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @myspec }
    end
  end

  # GET /myspecs/new
  # GET /myspecs/new.json
  def new
    @myspec = Myspec.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @myspec }
    end
  end

  # GET /myspecs/1/edit
  def edit
    @myspec = Myspec.find(params[:id])
  end

  # POST /myspecs
  # POST /myspecs.json
  def create
    @myspec = Myspec.new(params[:myspec])

    respond_to do |format|
      if @myspec.save
        format.html { redirect_to @myspec, notice: 'Myspec was successfully created.' }
        format.json { render json: @myspec, status: :created, location: @myspec }
      else
        format.html { render action: "new" }
        format.json { render json: @myspec.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /myspecs/1
  # PUT /myspecs/1.json
  def update
    @myspec = Myspec.find(params[:id])

    respond_to do |format|
      if @myspec.update_attributes(params[:myspec])
        format.html { redirect_to @myspec, notice: 'Myspec was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @myspec.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /myspecs/1
  # DELETE /myspecs/1.json
  def destroy
    @myspec = Myspec.find(params[:id])
    @myspec.destroy

    respond_to do |format|
      format.html { redirect_to myspecs_url }
      format.json { head :no_content }
    end
  end

  def coding
    @myspecs = Myspec.find(:all, :order => 'status')  

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @myspecs }
    end   
  end

  def stylingcss
    @myspecs = Myspec.find(:all, :order => 'status')  

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @myspecs }
    end   
  end

  def stylinghtml
    @myspecs = Myspec.find(:all, :order => 'status')  

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @myspecs }
    end   
  end

  def userfriendly
    @myspecs = Myspec.find(:all, :order => 'status')  

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @myspecs }
    end   
  end

  def cucumber
    @myspecs = Myspec.find(:all, :order => 'status')  

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @myspecs }
    end   
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/myspecs_helper.rb
module MyspecsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tracky</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Coding(Ruby)", myspecs_coding_path %></li>
            <li><%= link_to "Styling(CSS)", myspecs_stylingcss_path %></li>
            <li><%= link_to "Styling(HTML)", myspecs_stylinghtml_path %></li>
            <li><%= link_to "Userfriendlyness(Java)", myspecs_userfriendly_path %></li>
            <li><%= link_to "Testing(Cucumber)", myspecs_cucumber_path %></li>
            <%= link_to "Website App planning managment system v1.1", myspecs_path, :class => 'brand' %>
          </ul>
        </div>
      </div>
    </div>
  </div>

<div class="row-fluid">
  <div class="span2"></div>
  <div class="span8">
  <%= link_to "Home", myspecs_path %>
  <%= yield %>
  </div>
</div>

</body>
</html>

app/views/myspecs/_code.html.erb
<div class="field">
  <%= f.label :testing_status, "Ruby programming done?" %><br />
  <%= f.select(:testing_status, ["To be defined", "In progress", "Almost finished", "Finished"]) %>
</div>

<div class="field">
  <%= f.label :testing, "Ruby code" %><br />
  <%= f.text_area :testing, :class => "textarea" %>
</div>

app/views/myspecs/_form.html.erb
<h1>Soar on wings like eagles</h1>
<%= form_for(@myspec) do |f| %>
  <% if @myspec.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@myspec.errors.count, "error") %> prohibited this myspec from being saved:</h2>

      <ul>
      <% @myspec.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#home" data-toggle="tab">Functions</a></li>
  <li><a href="#code" data-toggle="tab">Code</a></li>
  <li><a href="#styling" data-toggle="tab">CSS</a></li>
  <li><a href="#java" data-toggle="tab">Javascript</a></li>
  <li><a href="#hypertext" data-toggle="tab">HTML</a></li>
  <li><a href="#testing" data-toggle="tab">Cucumber</a></li>
</ul>
 
<div class="tab-content">
  <div class="tab-pane active" id="home">
   <div class="field">
     <%= f.label :title %><br />
     <%= f.text_field :title %>
   </div>

    <div class="field">
     <%= f.label :core, "Core function?" %><br />
     <%= f.select(:core, ["No", "Yes"]) %>
   </div>
  
   <div class="field">
     <%= f.label :commit %><br />
     <%= f.text_field :commit %>
   </div>
  
   <div class="field">
     <%= f.label :overall_status, "Overall status of the feature" %><br />
     <%= f.select(:overall_status, ["To be defined", "In progress", "Halfway", "finished"] ) %>
   </div>

   <div class="field">
     <%= f.label :rating, "Overall rating, satisfied?" %><br />
     <%= f.select(:status, ["0","1", "2", "3", "4", "5", "6", "7", "8", "9", "10"] ) %>
   </div>

   <div class="field">
     <%= f.label :function, "Short function description" %><br />
     <%= f.text_area :function, :class => "textarea" %>
   </div>
  </div>
  
  <div class="tab-pane" id="code">
    <%= render :partial => 'code', :locals => { :f => f } %>
  </div>
  <div class="tab-pane" id="styling">
    <%= render :partial => 'styling', :locals => { :f => f } %>
  </div>
  <div class="tab-pane" id="java">
    <%= render :partial => 'java', :locals => { :f => f } %>
  </div>
  <div class="tab-pane" id="hypertext">
    <%= render :partial => 'hypertext', :locals => { :f => f } %>
  </div>
  <div class="tab-pane" id="testing">
    <%= render :partial => 'testing', :locals => { :f => f } %>
  </div>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/myspecs/_hypertext.html.erb
<div class="field">
  <%= f.label :hypertext_status, "HTML Status?" %><br />
  <%= f.select(:hypertext_status, ["To be defined", "In progress", "Almost finished", "Finished"]) %>
</div>

<div class="field">
  <%= f.label :hypertext, "HTML goes here" %><br />
  <%= f.text_area :hypertext, :class => "textarea" %>
</div>

app/views/myspecs/_java.html.erb
<div class="field">
  <%= f.label :coffee_status, "JavaScript status?" %><br />
  <%= f.select(:coffee_status, ["To be defined", "In progress", "Almost finished", "Finished"]) %>
</div>

<div class="field">
  <%= f.label :coffee, "Coffee or Javascript" %><br />
  <%= f.text_area :coffee, :class => "textarea" %>
</div>

app/views/myspecs/_styling.html.erb
<div class="field">
  <%= f.label :styling_status, "Styling status?" %><br />
  <%= f.select(:styling_status, ["To be defined", "In progress", "Almost finished", "Finished"]) %>
</div>

<div class="field">
  <%= f.label :styling, "CSS goes here" %><br />
  <%= f.text_area :styling, :class => "textarea" %>
</div>

app/views/myspecs/_testing.html.erb
<div class="field">
  <%= f.label :cucumber_status, "HTML Status?" %><br />
  <%= f.select(:cucumber_status, ["To be defined", "In progress", "Almost finished", "Finished"]) %>
</div>

<div class="field">
  <%= f.label :cucumber, "Cucumber specs goes here" %><br />
  <%= f.text_area :cucumber, :class => "textarea" %>
</div>

app/views/myspecs/coding.html.erb
<h1>Really great things happen in the blink on an eye..</i></h1>
<%= link_to 'New Myspec', new_myspec_path %>
<br />
<hr />

<table border="1" bgcolor="#D8D8D8">
<thead class="headingcolor">
<tr>
<th width="450pt" align="left">Feature</th>
<th width="150pt">Core Functionality?</th>
<th width="150pt">Ruby coding is..</th>
</tr>
</thead>
</table>

<% @myspecs.each do |myspec| %>
<table border="1" bgcolor="#D8D8D8">
<thead>
<tr>
<th width="450pt" align="left"><%= link_to myspec.title, myspec, {:style => "color:#0000FF;"} %></th>
<th width="150pt"><%= myspec.core %></th>
<th width="150pt"><%= myspec.testing_status %></th>
</tr>
</thead>
</table>


<% end %>

app/views/myspecs/cucumber.html.erb
<h1>Scientist say.. <i>"Everything is just light."</i></h1>
<%= link_to 'New Myspec', new_myspec_path %>
<br />
<hr />

<table border="1" bgcolor="#D8D8D8">
<thead class="headingcolor">
<tr>
<th width="450pt" align="left">Feature</th>
<th width="150pt">Core Functionality?</th>
<th width="150pt">Testing Status?</th>
</tr>
</thead>
</table>

<% @myspecs.each do |myspec| %>
<table border="1" bgcolor="#D8D8D8">
<thead>
<tr>
<th width="450pt" align="left"><%= link_to myspec.title, myspec, {:style => "color:#0000FF;"} %></th>
<th width="150pt"><%= myspec.core %></th>
<th width="150pt"><%= myspec.cucumber_status %></th>
</tr>
</thead>
</table>


<% end %>

app/views/myspecs/edit.html.erb
<h1>Editing myspec</h1>

<%= render 'form' %>

<%= link_to 'Show', @myspec %> |
<%= link_to 'Back', myspecs_path %>

app/views/myspecs/new.html.erb
<h1>New myspec</h1>

<%= render 'form' %>

<%= link_to 'Back', myspecs_path %>

app/views/myspecs/show.html.erb
<p id="notice"><%= notice %></p>
<center><h2><%= @myspec.title %></h2></center>
<%= link_to 'Edit', edit_myspec_path(@myspec) %> |
<%= link_to 'Back', myspecs_path %>
<hr />
<div class="row-fluid">
  <div class="span6">
   <p>
     <b>Feature status: <%= @myspec.overall_status %></b>
   </p>

   <p>
     <b>Core function?: <%= @myspec.core %></b>
   </p>
   
   <p>
     <b>Commit: <%= @myspec.commit %></b>
   </p>
   <p>
     <b>Overall rating: <%= @myspec.rating %></b>
   </p>
   <p>
     <b>Short functional summary:</b><br />
     <%= simple_format @myspec.function %>
   </p>
<hr />
   <p>
     <b>Ruby code done?: <%= @myspec.testing_status %></b>
   </p>
   <p>
     <b>Ruby code:</b><br />
     <%= simple_format @myspec.testing %>
   </p>
<hr />
   <p>
     <b>Cucumber testing specs done?: <%= @myspec.cucumber_status %></b>
   </p>
   <p>
     <b>Cucumber specs:</b><br />
     <%= simple_format @myspec.cucumber, :class => 'cucumber' %>
   </p>
<hr />
  </div>


  <div class="span6">
   <p>
     <b>CSS styling done?: <%= @myspec.styling_status %></b>
   </p>
   <p>
     <b>CSS stylesheet:</b><br />
     <%= simple_format @myspec.styling %>
   </p>
<hr />
   <p>
     <b>JavaScript (or coffeeScript) done?: <%= @myspec.coffee_status %></b>
   </p>
   <p>
     <b>Javascript/coffeeScript code:</b><br />
     <%= simple_format @myspec.coffee %>
   </p>
<hr />
   <p>
     <b>HTML codation done?: <%= @myspec.hypertext_status %></b>
   </p>
   <p>
     <b>(X)html code:</b><br />
     <%= simple_format @myspec.hypertext %>
   </p>
<hr />
  </div>
</div>
<hr />

<%= link_to 'Edit', edit_myspec_path(@myspec) %> |
<%= link_to 'Back', myspecs_path %>

app/views/myspecs/stylingcss.html.erb
<h1>With the endgoal in mind</h1>
<%= link_to 'New Myspec', new_myspec_path %>
<br />
<hr />

<table border="1" bgcolor="#D8D8D8">
<thead class="headingcolor">
<tr>
<th width="450pt" align="left">Feature</th>
<th width="150pt">Core Functionality?</th>
<th width="150pt">Styling Status?</th>
</tr>
</thead>
</table>

<% @myspecs.each do |myspec| %>
<table border="1" bgcolor="#D8D8D8">
<thead>
<tr>
<th width="450pt" align="left"><%= link_to myspec.title, myspec, {:style => "color:#0000FF;"} %></th>
<th width="150pt"><%= myspec.core %></th>
<th width="150pt"><%= myspec.styling_status %></th>
</tr>
</thead>
</table>


<% end %>

app/views/myspecs/stylinghtml.html.erb
<h1>More than just.. chemistry.</h1>
<%= link_to 'New Myspec', new_myspec_path %>
<br />
<hr />

<table border="1" bgcolor="#D8D8D8">
<thead class="headingcolor">
<tr>
<th width="450pt" align="left">Feature</th>
<th width="150pt">Core Functionality?</th>
<th width="150pt">Hypertext Status?</th>
</tr>
</thead>
</table>

<% @myspecs.each do |myspec| %>
<table border="1" bgcolor="#D8D8D8">
<thead>
<tr>
<th width="450pt" align="left"><%= link_to myspec.title, myspec, {:style => "color:#0000FF;"} %></th>
<th width="150pt"><%= myspec.core %></th>
<th width="150pt"><%= myspec.hypertext_status %></th>
</tr>
</thead>
</table>


<% end %>

app/views/myspecs/userfriendly.html.erb
<h1>They say good things take time.</h1>
<%= link_to 'New Myspec', new_myspec_path %>
<br />
<hr />

<table border="1" bgcolor="#D8D8D8">
<thead class="headingcolor">
<tr>
<th width="450pt" align="left">Feature</th>
<th width="150pt">Core Functionality?</th>
<th width="150pt">JavaScript/coffeeScript?</th>
</tr>
</thead>
</table>

<% @myspecs.each do |myspec| %>
<table border="1" bgcolor="#D8D8D8">
<thead>
<tr>
<th width="450pt" align="left"><%= link_to myspec.title, myspec, {:style => "color:#0000FF;"} %></th>
<th width="150pt"><%= myspec.core %></th>
<th width="150pt"><%= myspec.coffee_status %></th>
</tr>
</thead>
</table>


<% end %>